# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9f8239435f5aca611d5e5f3dd381183fabbb611fbd2383a6a16757a23feeb1f9c39bc0800a60eedd80375778e1fc9364ea01e7749ba11b14bab7f070038ffe9

test:
  secret_key_base: 2fded484de8593a69df535bf974dd9f5d521a7c3e7ab0c1401a2e1caf03221aa39faab38fcc4b1b6babb7f98d0a7b11ee16d475315bd3af55f6fce1a0eb0d955

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
